### PR TITLE
Add support for >= 2.3.0

### PR DESCRIPTION
**Pull request by ramereth**
Upstream refactored how Vagrant is installed from 2.3.0 and this cookbook didn't account for it. This provides proper support for this.

- Update default version to install to 2.3.4
- Logic fixes for installing >= 2.3.0
- CI and Cookstyle fixes
- Update tested platforms
- Standardize helper library and clean it up
- Cleanup and modernize unit tests

This supersedes #161

Signed-off-by: Lance Albertson <lance@osuosl.org>

### CODE REVIEW

**Review by Stromweld — DISMISSED** [review]
Wow that was a bit of work. Nice Job.

**Comment by ramereth** [comment]
> Wow that was a bit of work. Nice Job.

Not done :)

**Review by Stromweld — APPROVED** [review]
:)

**Comment by kitchen-porter** [comment]
Released as: [4.0.0](https://github.com/sous-chefs/vagrant/releases/tag/4.0.0)

**Pull request merged**
